### ISSUE TITLE
Searching for datasets

### ISSUE THREAD

**Issue by slaurila** [cms-opendata-workshop/workshopqcd-2024-lesson-dataset-scouting#3]
It looks like one can search for datasets simply with e.g.
`GluGluHToGG*` string, in addition to slightly more mysterious
`title.tokens:*GluGluHToGG*`
For simplicity, maybe we can drop "title.tokens"?

**Comment by katilp** [comment]
Oh cool, finally, they've updated the search! 
 The simple search did not work earlier.
 Thanks for checking!
